# Site settings
title: Portfolio - Shreedhar Todkar 
description: Shreedhar's portfolio, his life and career paths
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Shreedhar TODKAR
user_description: Currently, in position as R&D Technical Project Leader and AI Engineer with a strong background in AI for Autonomous Driving projects at Capgemini Engineering. Academic journey includes a PhD in Signal Processing, Geophysics, and Machine Learning, reflecting my expertise in data-driven technologies. With over 6 years of expertise in MATLAB and Python, along with 3 years in C++. Passionate in using AI and data engineering to drive innovation. Specialized in developing AI solutions and have a keen interest in Autonomous Vehicles and/or Health and Medicine.
user_title: Technical Project Lead | Data & AI Engineer | PhD. in AI, Signal Processing & Geophysics
email: shreedhar.todkar@gmail.com
twitter_username: shreedhar.todkar123
github_username:  shreedhartodkar
gplus_username:  lorem_ipsum
instagram_username : je_suis_shreedhar

# Google-analytics 
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
